@startuml

title Architecture IMUV Application

[Three.js] as TJS
note right
    3D-Engine
end note

[iTowns]
note top
Geospatial framework
end note

[ud-Viz] as udv
note left
Extension of itowns
end note

folder "Flying Campus / Imuv" {
    [Client]
    note bottom
    Render
    end note

    [Server]
    note bottom
    Connections, computations,
    node js
    end note

    interface websocket
    note bottom  
    Communication protocol
    end note
}


TJS -left-> iTowns
iTowns -down-> udv
udv -down-> Client
udv -down-> Server
websocket .left. Server
websocket .right. Client

@enduml