@startuml
title UD-Viz-Template Architecture

node "Node Server" {
  frame UD-Viz {
    [Three.js] as TJS
    note left
      3D-Engine
    end note

    [iTowns]
    note left
      Geospatial framework
    end note

    [Views] as view
    note left
      Extension of itowns
    end note

    [Components]
    [Game]
    [Widgets]
    [DeckGL]
  }
}

database "3DTiles-Server" {
  artifact "3DTiles data" as 3dt
  interface "REST API1" as api1
}

database "DeckGL Database" {
  artifact "DeckGL data" as dgl
  interface "REST API2" as api2
}

database "RDF-Store" {
  artifact "RDF data" as rdf
  interface "REST API3" as api3
}

TJS <-- iTowns : imports
TJS <-- DeckGL : imports
iTowns <-- view : imports
Components <-- view : imports
Components <-- Widgets : imports
Components <-- Game : imports
DeckGL <-- view : imports
view --> api1
view --> api2
Widgets --> api3
api1 -- 3dt
api2 -- dgl
api3 -- rdf
@enduml
